### ISSUE TITLE
LENDING FEATURE INTEGRATION FOR THIRD-PARTY DAPPS/INTERFACES

### ISSUE THREAD

**Issue by kcelestinomaria** [Folks-Finance/folks-finance-js-sdk#25]
Hey @gidonkatten @stefanofa @palace22 , we are trying to integrate lending infrastructure to our protocol, and enable our users to freely deposit and get loans on the equity of their tokenized assets. I lead the team at JASIRI(https://jasiriprotocol.org) , and we are an Algorand-based protocol under the Access/Impact vertical. Also reached out to you guys on your Twitter, and sent an inMail to Beneditto .

Curious if this is something you plan to enable on your SDKs as well, as I can only find gALGO feature enabled, but we are trying to connect with our own users' assets which are not cryptocurrencies, but equities on their own personal assets.

Looking forward to your response, or consideration.

Thanks!

**Comment by stefanofa** [comment]
Hey @kcelestinomaria you can find [here](https://github.com/Folks-Finance/folks-finance-js-sdk/tree/main/src/lend/v2) the part of the sdk relating to integration with the lending protocol!
