### ISSUE TITLE
request for documentation updates

### ISSUE THREAD

**Issue by kcelestinomaria** [Folks-Finance/folks-finance-js-sdk#28]
Hi Folks Team,

The docs for the SDK is a little bit scanty on detail, raised on Folks Discord a few days ago(**https://discord.com/channels/852212243596050433/942764016269426688/1109484946944426044**).

Having a hard time understanding the motivations for the SDK first of all:
1. Is it buit for developers who want to inherit the functionalities of the Folks Lending/Borrowing Protocol into new apps?
2. Can developers add their own assets, or those of their projects, like how developers can pool their own assets on Tinyman and AlgoFi, is there that freedom with Folks Finance, checked docs but I could only see USDC and gALGO are allowed. Are there any plans to allow that?

Will appreciate your assistance and guidance, as we would like to build with Folks Finance at jasiriprotocol.org .

Thanks!

**Comment by gidonkatten** [comment]
1. That could be one use case among others
2. No, asset listing is permissioned
