### ISSUE TITLE
prepareRegisterEscrowOnlineTransaction voteKeyAddr, selectionKeyAddr parameters: is this intended to be an address?

### ISSUE THREAD

**Issue by d13co** [Folks-Finance/folks-finance-js-sdk#30]
Hi,

I am trying to implement prepareRegisterEscrowOnlineTransaction and I got stuck on the voteKeyAddr and selectionKeyAddr parameters. Is this intended to be an address or is this a mistake in the SDK implementation? I would have expected a string or buffer there.

Normally from 'goal' you get the 32 byte key encoded in base64, are we meant to convert that to base32? Is it going to work as expected when registering it online?

If the SDK/ABI types are implemented correctly, it looks like we have to pass

```
const base64VotingKey = "pG2llJ0Bz2MQNp/zZU3iqBmyBC72xtTsq1P173ygcfw=";
const base32VotingKey = algosdk.encodeAddress(Buffer.from(base64VotingKey, "base64"));
```

If this is as-intended, adding something to the documentation to explain how to use is would be nice 👍

**Comment by gidonkatten** [comment]
Hey, we will update the function to accept a string which is expected to be a 32 byte key encoded in base64
