### ISSUE TITLE
LoanInfo UserAddress field not returning valid address

### ISSUE THREAD

**Issue by Jaybee020** [Folks-Finance/folks-finance-js-sdk#6]
Calling the isValidAddress function from the algosdk  module on UserAddress field in a loaning returning false

**Comment by gidonkatten** [comment]
That is strange. Can you share more details about what the LoanInfo was?

**Comment by Jaybee020** [comment]
let loansInfo = await getLoansInfo(indexerClient, tokenPair, tokenPairInfo, collateralPoolInfo, borrowPoolInfo,    conversionRate);
  let loans=loansInfo.loans
  console.log(loans.map((loan)=>isValidAddress(loan.userAddress)).reduce((a,b)=>a&&b,true))

The above returns false implying that the isValidAddress function returns false on the UserAddress property of a loan Object

**Comment by gidonkatten** [comment]
@Jaybee020 It appears the bug was with parsing the address from the global state. It should be resolved now
